spring:
  datasource:
    driver-class-name: ${DB_DRIVER}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
server:
  port: ${SERVER_PORT}
jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessExp: ${ACCESS_EXP}
  refreshExp: ${REFRESH_EXP}