name: fsg Ci

on:
  push:
    branches:
      - ["master"]
  pull_request:
    branches:
      - ["*"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create application.yml
        run: |
            rm ./src/main/resources/application.yml
            touch ./src/main/resources/application.yml
            echo "${{ secrets.APPLICATION_YML }}" >> ./src/main/resources/application.yml
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build --no-daemon

      - name: Test with Gradle
        run: ./gradlew test --no-daemon